export const AUTHENTICATION_MODULE_DISABLE_GUARDS_TOKEN =
  'AUTHENTICATION_MODULE_DISABLE_GUARDS_TOKEN';

// Port tokens
export const AUTHENTICATION_JWT_PORT_TOKEN = Symbol(
  '__AUTHENTICATION_JWT_PORT_TOKEN__',
);

export const AUTHENTICATION_TOKEN_PORT_TOKEN = Symbol(
  '__AUTHENTICATION_TOKEN_PORT_TOKEN__',
);

export const AUTHENTICATION_USER_PORT_TOKEN = Symbol(
  '__AUTHENTICATION_USER_PORT_TOKEN__',
);

export const AUTHENTICATION_PASSWORD_PORT_TOKEN = Symbol(
  '__AUTHENTICATION_PASSWORD_PORT_TOKEN__',
);

export const AUTHENTICATION_OTP_PORT_TOKEN = Symbol(
  '__AUTHENTICATION_OTP_PORT_TOKEN__',
);

export const AUTHENTICATION_RECOVERY_NOTIFICATION_PORT_TOKEN = Symbol(
  '__AUTHENTICATION_RECOVERY_NOTIFICATION_PORT_TOKEN__',
);

export const AUTHENTICATION_VERIFY_NOTIFICATION_PORT_TOKEN = Symbol(
  '__AUTHENTICATION_VERIFY_NOTIFICATION_PORT_TOKEN__',
);
