export const CACHE_MODULE_SETTINGS_TOKEN = 'CACHE_MODULE_SETTINGS_TOKEN';

export const CACHE_MODULE_DEFAULT_SETTINGS_TOKEN =
  'CACHE_MODULE_DEFAULT_SETTINGS_TOKEN';

export const CACHE_MODULE_CACHE_ENTITY_KEY = 'cache';

export const CACHE_REPOSITORY_RESOLVER_TOKEN =
  'CACHE_REPOSITORY_RESOLVER_TOKEN';
export const CACHE_CUSTOM_REPOSITORY_TOKEN = 'CACHE_CUSTOM_REPOSITORY_TOKEN';
