export const INVITATION_MODULE_SETTINGS_TOKEN =
  'INVITATION_MODULE_SETTINGS_TOKEN';

export const INVITATION_MODULE_DEFAULT_SETTINGS_TOKEN =
  'INVITATION_MODULE_DEFAULT_SETTINGS_TOKEN';

export const INVITATION_MODULE_DEFAULT_ENTITY_KEY = 'invitation';

export const INVITATION_MODULE_REPOSITORY_TOKEN =
  'INVITATION_MODULE_REPOSITORY_TOKEN';
