import { ClassTransformOptions } from 'class-transformer';

import { ValidationPipeOptions } from '@nestjs/common';

import { CrudParamsOptionsInterface } from './infrastructure/interfaces/crud-params-options.interface';

export const CRUD_MODULE_SETTINGS_TOKEN = 'CRUD_MODULE_SETTINGS_TOKEN';

export const CRUD_MODULE_DEFAULT_SETTINGS_TOKEN =
  'CRUD_MODULE_DEFAULT_SETTINGS_TOKEN';

export const CRUD_MODULE_CRUD_CONTEXT_KEY = 'CRUD_MODULE_CRUD_CONTEXT_KEY';

export const CRUD_MODULE_ROUTE_VALIDATION_METADATA =
  'CRUD_MODULE_ROUTE_VALIDATION_METADATA';

export const CRUD_MODULE_ROUTE_SERIALIZATION_METADATA =
  'CRUD_MODULE_ROUTE_SERIALIZATION_METADATA';

export const CRUD_MODULE_ROUTE_OPERATION_METADATA =
  'CRUD_MODULE_ROUTE_OPERATION_METADATA';

export const CRUD_MODULE_ROUTE_PARAMS_METADATA =
  'CRUD_MODULE_ROUTE_PARAMS_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_ALLOW_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_ALLOW_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_EXCLUDE_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_EXCLUDE_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_PERSIST_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_PERSIST_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_FILTER_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_FILTER_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_SORT_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_SORT_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_LIMIT_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_LIMIT_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_MAX_LIMIT_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_MAX_LIMIT_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_CACHE_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_CACHE_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_SOFT_DELETE_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_SOFT_DELETE_METADATA';

export const CRUD_MODULE_ROUTE_QUERY_JOIN_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_JOIN_METADATA';

// Request metadata keys
export const CRUD_MODULE_REQUEST_BODY_METADATA =
  'CRUD_MODULE_REQUEST_BODY_METADATA';

export const CRUD_MODULE_REQUEST_BODY_BATCH_METADATA =
  'CRUD_MODULE_REQUEST_BODY_BATCH_METADATA';

// Controller metadata keys
export const CRUD_MODULE_CONTROLLER_ENTITY_METADATA =
  'CRUD_MODULE_CONTROLLER_ENTITY_METADATA';

export const CRUD_MODULE_CONTROLLER_NAME_METADATA =
  'CRUD_MODULE_CONTROLLER_NAME_METADATA';

export const CRUD_MODULE_CONTROLLER_ADAPTER_METADATA =
  'CRUD_MODULE_CONTROLLER_ADAPTER_METADATA';

// Response metadata keys
export const CRUD_MODULE_RESPONSE_RESOURCE_METADATA =
  'CRUD_MODULE_RESPONSE_RESOURCE_METADATA';

export const CRUD_MODULE_RESPONSE_PAGINATED_METADATA =
  'CRUD_MODULE_RESPONSE_PAGINATED_METADATA';

// Return behavior metadata keys
export const CRUD_MODULE_ROUTE_RETURN_DELETED_METADATA =
  'CRUD_MODULE_ROUTE_RETURN_DELETED_METADATA';

export const CRUD_MODULE_ROUTE_RETURN_RESTORED_METADATA =
  'CRUD_MODULE_ROUTE_RETURN_RESTORED_METADATA';

export const CRUD_MODULE_ROUTE_ID_DEFAULT_PATH = ':id';

export const CRUD_MODULE_ROUTE_CREATE_MANY_DEFAULT_PATH = '/bulk';

export const CRUD_MODULE_ROUTE_RESTORE_DEFAULT_PATH =
  '/restore/' + CRUD_MODULE_ROUTE_ID_DEFAULT_PATH;

export const CRUD_MODULE_PARAM_BODY_METADATA =
  'CRUD_MODULE_PARAM_BODY_METADATA';

export const CRUD_MODULE_API_QUERY_METADATA = 'CRUD_MODULE_API_QUERY_METADATA';

export const CRUD_MODULE_API_PARAMS_METADATA =
  'CRUD_MODULE_API_PARAMS_METADATA';

export const CRUD_MODULE_API_RESPONSE_METADATA =
  'CRUD_MODULE_API_RESPONSE_METADATA';

// Query/Command metadata keys (classes to dispatch)
export const CRUD_MODULE_ROUTE_QUERY_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_METADATA';

export const CRUD_MODULE_ROUTE_COMMAND_METADATA =
  'CRUD_MODULE_ROUTE_COMMAND_METADATA';

// Handler metadata keys (handler classes for queries/commands)
export const CRUD_MODULE_ROUTE_QUERY_HANDLER_METADATA =
  'CRUD_MODULE_ROUTE_QUERY_HANDLER_METADATA';

export const CRUD_MODULE_ROUTE_COMMAND_HANDLER_METADATA =
  'CRUD_MODULE_ROUTE_COMMAND_HANDLER_METADATA';

// Resolver metadata keys
export const CRUD_MODULE_RESOLVER_METADATA = 'CRUD_MODULE_RESOLVER_METADATA';

export const CRUD_DEFAULT_RESOLVER_TOKEN = Symbol(
  'CRUD_DEFAULT_RESOLVER_TOKEN',
);

export const CRUD_MODULE_DEFAULT_PARAMS_OPTIONS: CrudParamsOptionsInterface<{
  id?: { field?: string };
}> = {
  id: { field: 'id', type: 'string', primary: true },
};

export const CRUD_MODULE_DEFAULT_TRANSFORM_OPTIONS: ClassTransformOptions = {
  strategy: 'excludeAll',
  excludeExtraneousValues: true,
  excludePrefixes: ['_', '__'],
};

export const CRUD_MODULE_DEFAULT_VALIDATION_PIPE_OPTIONS: ValidationPipeOptions =
  {
    transform: true,
    transformOptions: CRUD_MODULE_DEFAULT_TRANSFORM_OPTIONS,
  };

// CQRS tokens
export const CRUD_CONTEXT_PROVIDER_TOKEN = Symbol(
  'CRUD_CONTEXT_PROVIDER_TOKEN',
);
