export const FEDERATED_MODULE_SETTINGS_TOKEN =
  'FEDERATED_MODULE_SETTINGS_TOKEN';

export const FEDERATED_MODULE_DEFAULT_SETTINGS_TOKEN =
  'FEDERATED_MODULE_DEFAULT_SETTINGS_TOKEN';

export const FEDERATED_MODULE_DEFAULT_ENTITY_KEY = 'identity';

export const FEDERATED_MODULE_IDENTITY_REPOSITORY_TOKEN =
  'FEDERATED_MODULE_IDENTITY_REPOSITORY_TOKEN';
