export const USER_MODULE_SETTINGS_TOKEN = 'USER_MODULE_SETTINGS_TOKEN';
export const USER_MODULE_DEFAULT_SETTINGS_TOKEN =
  'USER_MODULE_DEFAULT_SETTINGS_TOKEN';
export const USER_MODULE_USER_PASSWORD_REUSE_AFTER_DAYS_DEFAULT = 365 * 2;

export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN';
export const USER_CREDENTIALS_REPOSITORY_TOKEN =
  'USER_CREDENTIALS_REPOSITORY_TOKEN';
