export const ACCESS_CONTROL_MODULE_SETTINGS_TOKEN =
  'ACCESS_CONTROL_MODULE_SETTINGS_TOKEN';

export const ACCESS_CONTROL_MODULE_DEFAULT_SETTINGS_TOKEN =
  'ACCESS_CONTROL_MODULE_DEFAULT_SETTINGS_TOKEN';

export const ACCESS_CONTROL_MODULE_GRANT_METADATA =
  'ACCESS_CONTROL_MODULE_GRANT_METADATA';

export const ACCESS_CONTROL_MODULE_QUERY_METADATA =
  'ACCESS_CONTROL_MODULE_QUERY_METADATA';

export const ACCESS_CONTROL_PORT_TOKEN = Symbol(
  '__ACCESS_CONTROL_PORT_TOKEN__',
);
