export const ROLE_MODULE_SETTINGS_TOKEN = 'ROLE_MODULE_SETTINGS_TOKEN';

export const ROLE_REPOSITORY_RESOLVER_TOKEN = 'ROLE_REPOSITORY_RESOLVER_TOKEN';
export const ROLE_ASSIGNMENT_REPOSITORY_RESOLVER_TOKEN =
  'ROLE_ASSIGNMENT_REPOSITORY_RESOLVER_TOKEN';
export const ROLE_CUSTOM_REPOSITORY_TOKEN = 'ROLE_CUSTOM_REPOSITORY_TOKEN';
export const ROLE_ASSIGNMENT_CUSTOM_REPOSITORY_TOKEN =
  'ROLE_ASSIGNMENT_CUSTOM_REPOSITORY_TOKEN';
