export const OTP_MODULE_SETTINGS_TOKEN = 'OTP_MODULE_SETTINGS_TOKEN';
export const OTP_MODULE_DEFAULT_SETTINGS_TOKEN =
  'OTP_MODULE_DEFAULT_SETTINGS_TOKEN';

export const OTP_REPOSITORY_RESOLVER_TOKEN = 'OTP_REPOSITORY_RESOLVER_TOKEN';
export const OTP_CUSTOM_REPOSITORY_TOKEN = 'OTP_CUSTOM_REPOSITORY_TOKEN';
